include: package:flutter_lints/flutter.yaml

analyzer: 
  errors: 
    missing_required_param: error 
    missing_return: error 
    always_declare_return_types: warning 

linter: 

  rules: 
    always_put_required_named_parameters_first: true 
    always_declare_return_types: true 
    avoid_redundant_argument_values: true 
    constant_identifier_names: true 
    file_names: true 
    prefer_is_empty : true
    prefer_is_not_empty : true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_int_literals: true
    sized_box_for_whitespace: true
    unawaited_futures: true