name: Alterar JSON com Base64

on:
  push:
    branches:
      - main

jobs:
  alterar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Decodificar Arquivo Base64
      id: decode
      run: |
        echo ${{ secrets.TEST_BASE64 }} | base64 -d > test.json
      shell: bash

    - name: Alterar o Arquivo JSON
      run: |
        echo "${{ secrets.ARQUIVO_JSON_BASE64 }}" | base64 -d > test.json
      shell: bash

    - name: Visualizar Alterações no Arquivo JSON
      run: |
        jq '.Teste = "novo_valor"' test.json > test.json
        cat test.json # Exibe o conteúdo do arquivo
      shell: bash

