name: Alterar JSON com Base64

on:
  push:
    branches:
      - main

jobs:
  alterar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Decodificar Arquivo Base64
      id: decode
      run: |
        echo ${{ secrets.TEST_BASE64 }} | base64 -d > test.json
      shell: bash

    - name: Alterar o Arquivo JSON
      run: |
        echo "${{ secrets.ARQUIVO_JSON_BASE64 }}" | base64 -d > test.json
      shell: bash

    - name: Commit e Push das Alterações
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add arquivo_modificado.json # ou o nome do arquivo que você alterou
        git commit -m "Atualização do arquivo JSON"
        git push
      shell: bash
